[
    { Id : 111, Name : 'Task 1', State : 'Backlog' },
    { Id : 1112, Name : 'Task 2', State : 'Backlog' },
    { Id : 1113, Name : 'Task 3', State : 'Backlog' },
    { Id : 1114, Name : 'Task 4', State : 'Backlog' },
    { Id : 1115, Name : 'Task 5', State : 'Backlog' },
    { Id : 1116, Name : 'Task 6', State : 'Backlog' },
    { Id : 1117, Name : 'Task 7', State : 'Backlog' },
    { Id : 1118, Name : 'Task 8', State : 'Backlog' },
    { Id : 1, Name : 'Fix IE7 bug', State : 'Backlog', ResourceId : 1 },
    { Id : 2, Name : 'Sneak-install Chrome Frame', State : 'NotStarted', NbrComments : 1, ResourceId : 1},
    { Id : 3, Name : 'Add Windows Phone support', State : 'Backlog', NbrComments : 1, ResourceId : 3},
    { Id : 4, Name : 'Make App', State : 'InProgress', NbrComments : 1},
    { Id : 5, Name : 'Find Unicorn', State : 'Test', ResourceId : 2},
    { Id : 6, Name : 'IE6 support', State : 'InProgress'},
    { Id : 7, Name : 'Chrome development', State : 'Done', Attachments : 1 },
    { Id : 8, Name : 'Find holy grail', State : 'Testing'},
    { Id : 9, Name : 'Dig hole', State : 'Testing'},
    { Id : 92, Name : 'Did it', State : 'TestingDone'},
    { Id : 93, Name : 'Works on my machine', State : 'TestingDone'},
    { Id : 94, Name : 'Think I tested this', State : 'TestingDone'},
    { Id : 10, Name : 'Eat raisins', State : 'Acceptance', NbrComments : 3, Attachments : 2},
    { Id : 11, Name : 'Do some cool task', State : 'Acceptance', NbrComments : 3, Attachments : 2},
    { Id : 12, Name : 'Eat raisins', State : 'Acceptance', NbrComments : 3, Attachments : 2},
    { Id : 13, Name : 'Fix hole in the roof', State : 'Done', NbrComments : 3, Attachments : 2},
    { Id : 14, Name : 'Change floor tiles', State : 'Done', NbrComments : 2, Attachments : 2},
    { Id : 15, Name : 'Uninstall IE', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'}
]