[
    { Id : 1, Name : 'Fix IE7 bug', State : 'NotStarted', ResourceId : 1, ImageUrl : 'img.jpeg' },
    { Id : 2, Name : 'Sneak-install Chrome Frame', State : 'NotStarted', NbrComments : 1, ResourceId : 1},
    { Id : 3, Name : 'Add Windows Phone support', State : 'InProgress', NbrComments : 1, ResourceId : 3},
    { Id : 4, Name : 'Make App', State : 'InProgress', NbrComments : 1},
    { Id : 5, Name : 'Find Unicorn', State : 'Test', ResourceId : 2},
    { Id : 6, Name : 'IE6 support', State : 'InProgress'},
    { Id : 7, Name : 'Chrome development', State : 'Done', Attachments : 1, ImageUrl : 'img2.jpeg'},
    { Id : 8, Name : 'Find holy grail', State : 'Done'},
    { Id : 9, Name : 'Dig hole', State : 'Done'},
    { Id : 10, Name : 'Eat raisins', State : 'Acceptance',ResourceId : 6, NbrComments : 3, Attachments : 2},
    { Id : 11, Name : 'Do some cool task', State : 'Acceptance', ResourceId : 7, NbrComments : 3, Attachments : 2},
    { Id : 12, Name : 'Eat raisins', State : 'Acceptance', NbrComments : 3, ResourceId : 6, Attachments : 2},
    { Id : 13, Name : 'Fix hole in the roof', State : 'Done', NbrComments : 3, Attachments : 2},
    { Id : 14, Name : 'Change floor tiles', State : 'Done', NbrComments : 2, Attachments : 2},
    { Id : 15, Name : 'Uninstall IE', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE5', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE6', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE7', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE8', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE9', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE10', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE11', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE12 Dev preview', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'},
    { Name : 'Uninstall IE12 Beta', State : 'Done', NbrComments : 67, Attachments : 400, Cls : 'special'}
]